---
  name: Build and Push OR check-PR

  on:
    pull_request:
      branches:
        - main
    push:
      branches:
        - main
        - dev
      tags:
        - "*"
    workflow_dispatch:
          
  jobs:
    compile_sketch:
      name: Build ${{ matrix.board.name }}
      runs-on: ubuntu-latest
      strategy:
        fail-fast: false
        matrix:
          board:     
            - {
                vendor: "CYD",
                name: "CYD-2432W328C",
                description: "(Capacitive)",
                link: "",
                family: "ESP32",
                env: "CYD-2432W328C",
                partitions: {
                  bootloader_addr: "0x1000",
                },
              }            
            - {
                vendor: "WIP",
                name: "CYD-8048S043C",
                description: "(ESP32S3, 4.3in, 800x480, Capacitive)",
                link: "",
                family: "ESP32-S3",
                env: "CYD-8048S043C",
                partitions: {
                  bootloader_addr: "0x0",
                },
              }
            - {
                vendor: "WIP",
                name: "CYD-8048W550C",
                description: "(ESP32S3, 5.5in, 800x480, Capacitive)",
                link: "",
                family: "ESP32-S3",
                env: "CYD-8048W550C",
                partitions: {
                  bootloader_addr: "0x0",
                },
              }            
            - {
                vendor: "Lilygo",
                name: "T-Deck",
                description: "(Normal and Plus)",
                link: "https://lilygo.cc/products/t-deck",
                family: "ESP32-S3",
                env: "lilygo-t-deck",
                partitions: {
                  bootloader_addr: "0x0",
                },
              }

      steps:
          - uses: actions/checkout@v4

          - id: build
            name: setup Python
            uses: actions/setup-python@v2
            with:
              python-version: "3.x"
          
          - name: Install dependencies
            run: | 
              pip install requests esptool
          
          - name: Install PlatformIO Core
            run: |
              pip install platformio

              if [[ "${{ github.ref_type }}" == "tag" ]]; then
                version=${{ github.ref_name }}
              else
                version="${GITHUB_SHA::7}"
              fi

              sed -i "s/-DLAUNCHER=/-DLAUNCHER='\"$version\"' ; /g" ./platformio.ini

          - name: Run Compile
            run: | 
              platformio run -e ${{ matrix.board.env }}

          - name: Merge files
            run: | 
                esptool.py --chip esp32s3 merge_bin -o Launcher-${{ matrix.board.env }}.bin \
                ${{ matrix.board.partitions.bootloader_addr }} .pio/build/${{ matrix.board.env }}/bootloader.bin \
                0x8000 .pio/build/${{ matrix.board.env }}/partitions.bin \
                0x10000 .pio/build/${{ matrix.board.env }}/firmware.bin
              
                js_content="{\"name\":\"${{ matrix.board.name }}\",\"builds\":[{\"chipFamily\":\"${{ matrix.board.family }}\",\"improv\":false,\"parts\":[{\"path\":\"bins/Launcher-${{ matrix.board.env }}.bin\",\"offset\":0}]}]}"
                echo "$js_content" > "./Manifest-${{ matrix.board.env }}.json"
                if [[ "${{ matrix.board.link }}" == "" ]]; then
                  html="<input type='radio' name='type' value='${{ matrix.board.env }}' id='${{ matrix.board.env }}' /><label for='${{ matrix.board.env}}'>${{ matrix.board.name }} ${{ matrix.board.description }}</label>"
                else
                  html="<input type='radio' name='type' value='${{ matrix.board.env }}' id='${{ matrix.board.env }}' /><label for='${{ matrix.board.env}}'>${{ matrix.board.name }} <a href='${{ matrix.board.link }}' target='_blank' rel='noopener noreferrer'>(link)</a> ${{ matrix.board.description }}</label>"
                fi
                echo "$html" > ./Launcher-${{ matrix.board.vendor }}.html

          - name: Upload Artifacts
            uses: actions/upload-artifact@v4
            with:
              name: Artifacts-${{ matrix.board.name }}
              path: |
                Launcher-*.bin
                Manifest-*.json
                Launcher-*.html
              retention-days: 5
              if-no-files-found: error
